name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  basic-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Check for syntax errors
        run: |
          python -m compileall .
          
      # Uncomment below when you're ready to add linting
      # - name: Lint with flake8
      #   run: |
      #     pip install flake8
      #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      
      # Uncomment below when you have tests
      # - name: Test with pytest
      #   run: |
      #     pip install pytest
      #     pytest

